version: '3.8'

services:
  # database
  postgresql-db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres@123
      - POSTGRES_DATABASE=OnlineClothe
      

  pgbouncer:
    ports:
      - "6432:6432"
    environment:
      - POSTGRESQL_HOST=postgresql-db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres@123
      - POSTGRESQL_DATABASE=OnlineClothe
      - PGBOUNCER_PORT=6432
      - PGBOUNCER_BIND_ADDRESS=0.0.0.0
      - PGBOUNCER_EXTRA_FLAGS=--verbose
      - PGBOUNCER_DATABASE=OnlineClothe
      - PGBOUNCER_DEFAULT_POOL_SIZE=50


  mail-server-smtp:
    ports:
      - "2500:2500"
      - "8080:8080"
      - "8085:8085"


  app:
    build: .
    image: solcr/online-clothes-api:dev
    ports:
      - "9080:80"
      - "9443:443"
    depends_on:
      - pgbouncer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/.https/localhost.pfx
    env_file:
      - ./docker/.env

